#!/usr/bin/env python3

import os
import argparse
from pathlib import Path

""" USAGE INFORMATION / README
Meant to be ran on logs directory generated by the scram_slurmarray.py script, SCRAM file conversion jobs are successfully completed if nothing is outputted by this script.

ARGUMENTS:
    --logs_dir  absolute path to directory containing scram conversion log files

Example usage:
/groups/wyattgrp/users/zshong/projects/to_scram/check_scram.py \
    --logs_dir /groups/wyattgrp/users/zshong/projects/to_scram/to_backup/logs


================================================================      
END USAGE INFORMATION  Author: Zoe Shong
"""
def get_last_line(file_path):
    with open(file_path, "rb") as f:
        f.seek(-2, os.SEEK_END)
        while f.read(1) != b"\n":
            f.seek(-2, os.SEEK_CUR)
        return f.readline().decode().strip()

def check_complete(logs_dir):
    for file in os.listdir(logs_dir):
        file_path = os.path.join(logs_dir, file)
        last_line = get_last_line(file_path)
        if last_line != "SCRAM conversion successfully completed...":
            print(f"SCRAM conversion for {file_path} did not complete successfully...")
        

def main():
    parser = argparse.ArgumentParser(
        description="Checks if all scram files have been converted successfully by iterating through log files"
    )

    parser.add_argument("--logs_dir", required=True, help="Directory containing scram conversion log files")

    args = parser.parse_args()

    # check if the given logs directory exists 
    if os.path.isdir(args.logs_dir):
        check_complete(args.logs_dir)
    else:
        raise ValueError('Given logs directory does not exist or is invalid...')


if __name__ == "__main__":
    main()